### ISSUE TITLE
Is this the official address of your software?

### ISSUE THREAD

**Issue by xujingmei111** [zhongguojie1998/CSOmap#1]
The software link in your paper "Reconstruction of cell spatial organization from single-cell RNA sequencing data based on ligand-receptor mediated self-assembly" is invalid.
R packages will be more widely used in the field of bioinformatics instead of Matlab.Have you thought about perfecting it?

**Comment by zhongguojie1998** [comment]
The software link in our paper is a capsule in CodeOcean, we choose that platform for the convenience of reviewers and to ensure reproductivity. I checked it on my computer and it should work, could you please try to copy and paste the link to your browser instead of clicking that link in the PDF viewer? Sometimes the PDF viewer can fail to resolve the link.

And yes, this is also the official address of our software, we uploaded the R version here. You can refer to the CSOmap.R/ folder. The R version only supports the fundamental algorithm but does not support visualization. It will return all the outputs in a list object. We suggest using the matlab version if you would like to visualize and produce figures, otherwise R version should be enough.
